exclude: 'data|docs|outputs'
default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-added-large-files
        args: [ --maxkb=15000 ]
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
        types: [ python ]

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        types: [ python ]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings
        types: [ python ]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.3.9
    hooks:
      - id: nbstripout
        files: '.ipynb'

  - repo: local
    hooks:
      - id: requirements.txt
        name: Generate requirements.txt
        entry: poetry export
        args:
          [ '-f', 'requirements.txt', '-o', 'requirements.txt', '--without-hashes' ]
        pass_filenames: false
        language: system
        files: 'poetry.lock'
