# @package _group_

datamodule:
  _target_: deep_learning_template.datamodules.mnist.MNISTDataModule
  normalize: True

authorized_tasks:
  - _target_: deep_learning_template.tasks.representation_learning.PixelWiseAutoencodingTask