# @package _group_

datamodule:
  _target_: deep_learning_tutorials.datamodules.mnist.MNISTDataModule
  normalize: True

authorized_tasks:
  - _target_: deep_learning_tutorials.tasks.representation_learning.PixelWiseAutoencodingTask